project:
  type: book

book:
  title: ""
  author: ""
  date: ""
  chapters:
    - index.qmd
    - DeliverablesSchedule.qmd
    - ProjectLifeCycle.qmd
    - References.qmd

bibliography: references.bib

format:
  html:
    number-sections: false
    theme:
      - cosmo
      - brand
  pdf:
    number-sections: false
    documentclass: scrreprt

params:
  projectReference: "https://irma.nps.gov/DataStore/Reference/Profile/2216938"


